all: and_module_example.v
	iverilog and_module_example.v -Wall -o and_module_example.vvp
	@echo "Now, run the file and_module_example.vvp and open the .vcd file it generates using gtkwave to see"
	@echo "what the circuit described in and_module_example.v did."
