all: majority_voter_exercise.v
	iverilog majority_voter_exercise.v -Wall -o majority_voter_exercise.vvp
	@echo "Now, run the file majority_voter_exercise.vvp and open the .vcd file it generates using gtkwave to see"
	@echo "what the circuit described in majority_voter_exercise.v did."
