all: sum_example.v
	iverilog sum_example.v -Wall -o sum_example.vvp
	@echo "Now, run the file sum_example.vvp and open the .vcd file it generates using gtkwave to see"
	@echo "what the circuit described in sum_example.v did."
