all: and_example.v
	iverilog and_example.v -Wall -o and_example.vvp
	@echo "Now, run the file and_example.vvp and open the .vcd file it generates using gtkwave to see"
	@echo "what the circuit described in and_example.v did."
