all: multiplexer_example.v
	iverilog multiplexer_example.v -Wall -o multiplexer_example.vvp
	@echo "Now, run the file multiplexer_example.vvp and open the .vcd file it generates using gtkwave to see"
	@echo "what the circuit described in multiplexer_example.v did."
