all: saturating_adder_exercise.v
	iverilog saturating_adder_exercise.v -Wall -o saturating_adder_exercise.vvp
	@echo "Now, run the file saturating_adder_exercise.vvp and open the .vcd file it generates using gtkwave to see"
	@echo "what the circuit described in saturating_adder_exercise.v did."
